### PR TITLE
Added functionality that allows user to delete uploaded image using the password used for upload

### PR DESCRIPTION
**Pull request by Boobeshkumar56**

### CODE REVIEW

**Comment by KorryKatti** [comment]
will test and merge soon , thanks for the PR

**Comment by Boobeshkumar56** [comment]
let me know if anything i could contribute in this project

**Comment by KorryKatti** [comment]
> let me know if anything i could contribute in this project

sure will

**Comment by KorryKatti** [comment]
hey @Boobeshkumar56 could you sync the repo once and resubmit a pr as some changes were made to main.py by the previous PR. sorry for the inconvenience

**Pull request closed without merging**
